name: pets
description: NAPR Pet Registration app.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  numeric_keyboard: ^1.0.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  fluttertoast: ^8.1.1
  animated_splash_screen: ^1.1.0
  dropdown_button2: ^2.3.9
  radio_group_v2: ^3.1.1
  flutter_radio_group: ^2.1.0
  loader_skeleton: ^0.0.4
  flicked_cards: ^0.0.3
  animated_button: ^0.2.0
  pin_code_fields: ^8.0.1
  retrofit: '>=3.0.0 <4.0.0'
  logger: any
  image_picker: ^1.0.7
  path_provider: ^2.0.11
  flutter_styled_toast: ^2.1.3
  flutter_list_view: ^1.1.21
  pull_to_refresh: ^2.0.0
  http: ^1.2.0
  shared_preferences: ^2.0.15
  flutter_easyloading: ^3.0.5
  lottie: ^2.1.0
  flutter_loadingindicator: ^1.0.1
  row_item: ^2.1.0
  photo_view: ^0.15.0
  advance_pdf_viewer_fork: ^2.0.0
  dropdown_textfield: ^1.0.7
  dropdown_search: ^5.0.6
  simple_radio_group: ^1.0.0
  flutter_webview_pro: ^3.0.1+4
  material_dialogs: ^1.1.4
  payu_checkoutpro_flutter: ^1.0.0
  stylish_dialog: ^1.0.1
  flutter_spinkit: ^5.1.0
  time_converter: ^0.0.1
  intl: ^0.19.0
  group_radio_button: ^1.3.0
  custom_searchable_dropdown: ^2.1.1
  app_dialog: ^1.1.0
  url_launcher: ^6.1.7
  awesome_dialog: ^3.0.2
  sn_progress_dialog: ^1.1.2
  permission_handler: ^11.3.1
  cached_network_image: ^3.2.3
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^17.1.2
  location_plus: ^1.0.6
  ndialog: ^4.3.0
  proste_dialog: ^2.1.2
  dialog_kh: ^0.0.1
  open_file: ^3.3.2
  checkbox_formfield: ^0.2.0
  rounded_loading_button_plus: ^3.0.1
#  pdfdownload: ^0.0.2


dev_dependencies:
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>2.3.0 <4.0.0'
  json_serializable: '>4.4.0'
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
